# Student Grades — Data Cleaning & Exploratory Analysis
### Built with Python and Pandas

In [21]:
# 1 importing pandas

In [22]:
import pandas as pd

In [23]:
# 2 importing grade.csv file

In [24]:
df1=pd.read_csv('grades.csv')

In [25]:
#3 Displaying top 10 rows

In [26]:
df1.head(10)

   ID                 Name   GPA              Major
0  23            Rose Rios  3.97          Economics
1  55            Ian Brown  1.44  Political Science
2  54         Stanley Dean  3.75         Philosophy
3  19  Stephanie Henderson  1.86        Mathematics
4  81          Angela Mora  3.86            Physics
5  60          Mark Martin  1.47          Chemistry
6  47     Jennifer Perkins  2.88            English
7  11      William Stewart  1.27            Biology
8  34           Eric Moore  3.40            Spanish
9  70      Kenneth Rollins  2.37                Art

In [ ]:
# 4 Displaying bottom 10 rows

In [33]:
df1.tail(10)

    ID                   Name   GPA        Major
90  72            Joseph Beck  1.56      Spanish
91  18        Alexandra Green  3.12          Art
92  65  Christopher Hernandez  2.08      History
93  78       William Caldwell  2.79   Philosophy
94  20            Diane Brown  1.73  Mathematics
95  41       Brenda Valentine  3.10      Physics
96  86          Grace Hoffman  1.30    Chemistry
97  10            Joshua Ware  3.29      English
98  61        Samantha Steele  2.56      Spanish
99  22              Lisa Chen  1.45          Art

In [ ]:
# 5 Displaying variable names, counts and data types

In [37]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      100 non-null    int64
 1   Name    100 non-null    object
 2   GPA     100 non-null    float64
 3   Major   100 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 3.2+ KB

In [ ]:
# 6 Displaying summary statistics

In [39]:
df1.describe()

               ID         GPA
count  100.000000  100.000000
mean    50.500000    2.476500
std     29.011492    0.823619
min      1.000000    1.030000
25%     25.750000    1.775000
50%     50.500000    2.475000
75%     75.250000    3.172500
max    100.000000    3.970000

In [ ]:
# 7 checking for duplicate rows

In [62]:
df1 = pd.read_csv("grades.csv")

In [70]:
duplicates = df1[df1.duplicated()]
duplicates

Empty DataFrame
Columns: [ID, Name, GPA, Major]
Index: []

In [ ]:
# 8 dropping duplicate rows

In [82]:
df1 = df1.drop_duplicates()

# Verifying duplicates are removed
df1[df1.duplicated()]

Empty DataFrame
Columns: [ID, Name, GPA, Major]
Index: []

In [ ]:
# 9 Finding missing values

In [78]:
missing = df1.isnull().any(axis=1)
df1[missing]

Empty DataFrame
Columns: [ID, Name, GPA, Major]
Index: []

In [ ]:
# 10 dropping rows with missing values

In [86]:
df1 = df1.dropna()

# Verifying that no missing values remain
df1.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool